version: "3.8"

volumes:
  postgres-data:

services:
  python_bot:
    build: ./python_bot
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "Crjhjcnm1"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080