name: Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Docker Compose stop
        run: docker-compose down
      - name: Docker Compose Build and Run
        run: docker-compose up
